# Generated by Django 6.0 on 2026-01-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_transactionitem_paid_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionitem',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='transactionitem',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='transaction',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
